import { toTestId } from 'src/utils/base.js'

export const telehealthTestIds = {
  lobbyJoin: 'telehealth-lobby-btn-join',
  lobbyBack: 'telehealth-lobby-btn-back',
  lobbyDeviceClose: 'telehealth-lobby-device-btn-close',
  endedComplete: 'telehealth-ended-btn-complete',
  endedLeave: 'telehealth-ended-btn-leave',
  endedBack: 'telehealth-ended-btn-back',
  inCallMute: 'telehealth-incall-btn-mute',
  inCallVideo: 'telehealth-incall-btn-video',
  inCallSpeaker: 'telehealth-incall-btn-speaker',
  inCallScreen: 'telehealth-incall-btn-screen',
  inCallChat: 'telehealth-incall-btn-chat',
  inCallMinimize: 'telehealth-incall-btn-minimize',
  inCallLeave: 'telehealth-incall-btn-leave',
  floatMute: 'telehealth-float-btn-mute',
  floatVideo: 'telehealth-float-btn-video',
  floatRestore: 'telehealth-float-btn-restore',
  chatSend: 'telehealth-chat-btn-send',
  chatDelete: id => toTestId('telehealth-chat-btn-delete', id),
  fileDownload: id => toTestId('telehealth-file-btn-download', id),
  fileDelete: id => toTestId('telehealth-file-btn-delete', id),
  copyInvite: 'telehealth-btn-copy-invite',
  resendInvite: 'telehealth-btn-resend-invite',
  admit: id => toTestId('telehealth-btn-admit', id),
  waitingStart: 'telehealth-waiting-btn-start',
  waitingLeave: 'telehealth-waiting-btn-leave',
  waitingCopyInvite: 'telehealth-waiting-btn-copy-invite',
  deviceCamera: 'telehealth-device-btn-camera',
  deviceMic: 'telehealth-device-btn-mic',
  deviceSpeaker: 'telehealth-device-btn-speaker',
  signPage: 'consent-sign-page',
  signMode: 'consent-sign-mode',
  signSubmit: 'consent-sign-btn-submit',
  signDecline: 'consent-sign-btn-decline',
}
